# Site settings
title: DTU BioBuilders
email: hello@biobuilders.net
url: https://example.github.io
description: "Students solving problems with synthetic biology" # Description on first page

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#003024'
  links: '#0b6623'

# Footer settings
footer: DTU BioBuilders

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/dtubiobuilders
  - title: instagram
    url: https://www.instagram.com/igem_dtubiobuilders
  - title: github
    url: https://github.com/https://github.com/jcd12/biobuilders-site

# Build settings
markdown: kramdown
permalink: pretty
