# Site settings
title: Title in tab
email: hello@biobuilders.net
url: https://example.github.io
description: "Welcome to the website for the DTU BioBuilders of 2020!" # Description on first page

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: DTU BioBuilders

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/dtubiobuilders
  - title: github
    url: https://github.com/https://github.com/jcd12/biobuilders-site

# Build settings
markdown: kramdown
permalink: pretty
